# конфигурационный файл для сборки проекта

name: Test # имя workflow-а

on:# прописываем триггеры для нашего workflow-a
  pull_request:
    paths:
      - '**.kt'
      - '**.yml'
  push:
	  paths:
	    - '**.kt'
      - '**.yml'

jobs: # перечисляем задания, каждое из которых запускается на отдельном docker-контейнере,
			# с развернутым на нём образом выбранной далее ОС
  test:
    runs-on: ubuntu-latest # выбрали окружение
    steps: # последовательность действий, которые нужно выполнить в docker-контейнере
				   # gitActions позволяет использовать готовые логические блоки команд, называемые action-ами
      - name: Check out repository code
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
      - name: Build 
      - run: ./gradlew build -x test # прогоняем только сборку без запуска автотестов
      - name: Test
      - run: ./gradlew test 
      - name: Upload coverage reports to Codecov
				uses: codecov/codecov-action@v4
				with:
					token: ${{ secrets.CODECOV_TOKEN }}